knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        facebook:
            type: facebook
            client_id: '%facebook.client_id%'
            client_secret: '%facebook.client_secret%'
            redirect_route: connect_facebook_check
            redirect_params: {}
            graph_api_version: v3.0
        google:
            type: google
            client_id: '%google.client_id%'
            client_secret: '%google.client_secret%'
            redirect_route: connect_google_check
            redirect_params: {}
